[project]
name = "ss"
version = "1.1.1"
description = "Windows 音频分流工具，将输入音频的左右声道分别输出到两个设备，支持音量跟随和延迟调整。"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "av>=19.0.0",
    "comtypes>=1.4.17",
    "dishka>=1.10.1",
    "pycaw>=20260927",
    "pydantic>=2.13.5",
    "pydantic-yaml>=1.7.0",
    "pyside6>=6.11.2",
    "shiboken6>=6.11.2",
]

[project.scripts]
ss = "ss:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "deptry>=0.25.1",
    "nuitka>=4.2.2",
    "ordered-set>=4.1.0",
    "pyright>=1.1.414",
    "ruff>=0.16.10",
    "zstandard>=0.25.0",
]

[tool.ruff]
extend-exclude = [
    "src/ss/integration/app/resources",
    "src/ss/integration/app/ui",
]
force-exclude = true

[tool.pyright]
exclude = [
    "src/ss/integration/app/resources",
    "src/ss/integration/app/ui",
]
ignore = [
    "src/ss/integration/app/resources",
    "src/ss/integration/app/ui",
]

[tool.deptry]
exclude = [
    "src/ss/integration/app/resources",
    "src/ss/integration/app/ui",
]
